"""
@file generate_symbol_index.py
@brief Generates reproducible source declaration links for file-header documentation.
@details Function and variable locations are indexed by the output this script creates.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPOSITORY_ROOT / "docs" / "generated" / "symbol-index.md"
INCLUDED_EXTENSIONS = {".cpp", ".hpp", ".py", ".sh"}
SKIPPED_DIRECTORIES = {".git", "build", "out", "reports", "generated"}
PATTERNS = [
    re.compile(r"^\s*(?:class|struct|enum(?:\s+class)?)\s+([A-Za-z_][A-Za-z0-9_]*)"),
    re.compile(r"^\s*(?:def|class)\s+([A-Za-z_][A-Za-z0-9_]*)"),
    re.compile(r"^\s*IMLP_TEST\(([A-Za-z_][A-Za-z0-9_]*)\)"),
    re.compile(r"^\s*(?:function)\(([A-Za-z_][A-Za-z0-9_]*)"),
    re.compile(
        r"^(?:\[\[nodiscard\]\]\s+)?(?:extern\s+\"C\"\s+)?(?:inline\s+)?(?:static\s+)?"
        r"(?:constexpr\s+)?"
        r"[A-Za-z_][A-Za-z0-9_:<>,\s*&]*\s+([A-Za-z_][A-Za-z0-9_:]*)\s*\("
    ),
]


def discover_source_files() -> list[Path]:
    """Return stable, repository-relative source candidates."""
    files: list[Path] = []
    for path in REPOSITORY_ROOT.rglob("*"):
        relative = path.relative_to(REPOSITORY_ROOT)
        if any(part in SKIPPED_DIRECTORIES or part.startswith("build-") for part in relative.parts):
            continue
        if path.is_file() and (path.suffix in INCLUDED_EXTENSIONS or path.name == "CMakeLists.txt"):
            files.append(path)
    return sorted(files, key=lambda path: path.relative_to(REPOSITORY_ROOT).as_posix().casefold())


def symbols_for(source: str) -> list[tuple[str, int]]:
    """Extract unique named declarations with exact one-based line numbers."""
    symbols: list[tuple[str, int]] = []
    seen: set[str] = set()
    for line_number, line in enumerate(source.splitlines(), start=1):
        for pattern in PATTERNS:
            match = pattern.search(line)
            if match and match.group(1) not in seen:
                name = match.group(1)
                seen.add(name)
                symbols.append((name, line_number))
                break
    return symbols


def render() -> str:
    """Render the complete Markdown index with repository-relative links."""
    sections: list[str] = []
    for path in discover_source_files():
        relative = path.relative_to(REPOSITORY_ROOT).as_posix()
        source = path.read_text(encoding="utf-8")
        symbols = symbols_for(source)
        if symbols:
            rows = "\n".join(
                f"- `{name}` — [line {line}](../../{relative}#L{line})" for name, line in symbols
            )
        else:
            rows = "- No named declaration; see the file-level header at line 1."
        sections.append(f"### `{relative}`\n\n{rows}")
    return (
        "<!-- Generated by scripts/generate_symbol_index.py. Do not edit by hand. -->\n\n"
        "# Source symbol index\n\n"
        "This index supplies exact line locations for the classes, functions, tests, and important "
        "declarations summarized by each source file header. Regenerate it after source changes with "
        "`python scripts/generate_symbol_index.py`; CI rejects stale output.\n\n"
        + "\n\n".join(sections)
        + "\n"
    )


def main() -> int:
    """Write the index or compare it byte-for-byte when --check is supplied."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = render()
    if arguments.check:
        existing = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if existing != generated:
            print("docs/generated/symbol-index.md is stale", file=sys.stderr)
            return 1
        return 0
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(generated, encoding="utf-8")
    print(f"Indexed {len(discover_source_files())} source files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
